### ISSUE TITLE
It seems like that Tensorflow can not be imported

### ISSUE THREAD

**Issue by duohongrui** [imsb-uke/scGAN#15]
Hi, scGAN is very uesful within my research pipeline and I have being learning and testing it these days. But there is a confusing problem that hardly be solved.
I pulled the docker image from DockerHub, created a container, altered the `parameters.json` file and copied the `data.h5ad` file into the container. However, when I ran the following command the error occurred.

```
docker create -it --name="scGAN_test" bac785b4b3ea /bin/bash
```
```
docker cp ./parameters.json 9b1:/scGAN
docker cp ./data.h5ad 9b1:/scGAN
```
```
docker exec -it 9b14556fefc4 python main.py
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from estimators.run_exp import run_exp
  File "/scGAN/estimators/run_exp.py", line 3, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
It seems like that importing the Tensorflow may be wrong or because of my wrong manipulations. How to solve it? 
Thanks so much!

**Comment by fhausmann** [comment]
Hello @duohongrui, 
scGANs implementation requires a NVIDIA GPU available. 
You can make it available through docker's `--gpus` flag in any recent docker version.
If you're using an older docker version, you need to use `nvidia-docker2` command as replacement for docker. 
Please check https://www.tensorflow.org/install/docker?hl=en for more information.
